# =====================================================================
# supabase/config.toml — Asraya OS (Corrected)
# =====================================================================

# ---------------------------------------------------------------------
# Project reference (must match your Supabase dashboard “Project Ref”)
# ---------------------------------------------------------------------
project_id = "xdkadojhsteiecbqjgro"

# ---------------------------------------------------------------------
# API  (PostgREST)
# ---------------------------------------------------------------------
[api]
enabled           = true
port              = 54321
schemas           = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows          = 1000

  [api.tls]  # HTTPS off for local dev
  enabled = false

# ---------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------
[db]
port          = 54322
shadow_port   = 54320
major_version = 15

  [db.pooler]          # PgBouncer (disabled locally)
  enabled           = false
  port              = 54329
  pool_mode         = "transaction"
  default_pool_size = 20
  max_client_conn   = 100

[db.migrations]
schema_paths = []      # we manage via supabase/migrations/*.sql

[db.seed]
enabled   = true
sql_paths = ["./seed.sql"]

# ---------------------------------------------------------------------
# Realtime & Studio
# ---------------------------------------------------------------------
[realtime]
enabled = true

[studio]
enabled        = true
port           = 54323
api_url        = "http://localhost"
openai_api_key = "env(OPENAI_API_KEY)"

# ---------------------------------------------------------------------
# Email sandbox (Inbucket)
# ---------------------------------------------------------------------
[inbucket]
enabled = true
port    = 54324

# ---------------------------------------------------------------------
# Storage
# ---------------------------------------------------------------------
[storage]
enabled         = true
file_size_limit = "50MiB"

# ---------------------------------------------------------------------
# Authentication  (GoTrue)
# ---------------------------------------------------------------------
[auth]
enabled                     = true
site_url                    = "http://localhost:3000"
additional_redirect_urls    = [
  "http://localhost:3000",
  "http://localhost:3001/**", "http://localhost:3002/**",
  "http://localhost:3003/**", "http://localhost:3004/**",
  "http://localhost:3005/**", "http://localhost:3006/**",
  "http://localhost:3007/**", "http://localhost:3008/**",
  "http://localhost:3009/**", "http://localhost:3010/**"
]
jwt_expiry                  = 7200      # 2 h
enable_refresh_token_rotation = true
refresh_token_reuse_interval  = 10
enable_signup               = true
enable_anonymous_sign_ins   = false
enable_manual_linking       = false
minimum_password_length     = 6
password_requirements       = ""

  [auth.rate_limit]
  email_sent          = 2
  sms_sent            = 30
  anonymous_users     = 30
  token_refresh       = 150
  sign_in_sign_ups    = 30
  token_verifications = 30

  [auth.email]
  enable_signup        = true
  double_confirm_changes = true
  enable_confirmations   = false     # set true in production
  secure_password_change = false
  max_frequency        = "1s"
  otp_length           = 6
  otp_expiry           = 86400     # 24 h

  [auth.sms]
  enable_signup        = false
  enable_confirmations = false
  template             = "Your code is {{ .Code }}"
  max_frequency        = "5s"

    [auth.sms.twilio]
    enabled             = false
    account_sid         = ""
    message_service_sid = ""
    auth_token          = "env(SUPABASE_AUTH_SMS_TWILIO_AUTH_TOKEN)"

  [auth.mfa]
  max_enrolled_factors = 10

    [auth.mfa.totp]
    enroll_enabled = false
    verify_enabled = false

    [auth.mfa.phone]
    enroll_enabled = false
    verify_enabled = false
    otp_length     = 6
    template       = "Your code is {{ .Code }}"
    max_frequency  = "5s"

  [auth.external.apple]
  enabled = false
  # add other providers as needed …

# ---------------------------------------------------------------------
# Edge runtime & local analytics
# ---------------------------------------------------------------------
[edge_runtime]
enabled        = true
policy         = "oneshot"
inspector_port = 8083
deno_version   = 1 # Assuming this is a valid key for your setup; standard is often managed by Supabase itself.

[analytics]
enabled = true
port    = 54327
backend = "postgres"

# -----------------------------------------------------------------
# EDGE FUNCTIONS (Corrected based on CLI compatibility and CORS strategy)
# -----------------------------------------------------------------
[functions.list-quests]
enabled             = true
# name key removed - invalid for this CLI version
verify_jwt          = false # Allows OPTIONS to pass through; JWT manually checked in function for POST/other methods
# invoke_http_methods key removed - invalid for this CLI version
entrypoint          = "./functions/list-quests/index.ts"

[functions.create-quest]
enabled             = true
# name key removed - invalid for this CLI version
verify_jwt          = false # Allows OPTIONS to pass through; JWT manually checked in function for POST/other methods
# invoke_http_methods key removed - invalid for this CLI version
entrypoint          = "./functions/create-quest/index.ts"

# ---------------------------------------------------------------------
# (Add more function blocks below as needed, following the pattern above)
# ---------------------------------------------------------------------